### ISSUE TITLE
Crash On FindObjectsOfType

### ISSUE THREAD

**Issue by hellotheresanta** [sneakyevil/IL2CPP_Resolver#46]
Hello, i've been toying with this il2cpp_resolver and gotten some basic stuff to work. but after a minute or 2 my game kept crashing. upon repeatedly inspecting what might've happened. it appears this is the last line of code that is attempted to execute before the program crashes. not always but guaranteed once every 5 minutes or so requiring me to restart my game.

![image](https://github.com/sneakyevil/IL2CPP_Resolver/assets/69880496/2be2a12a-e68d-4c5f-a2b4-f6ad3b5ddec1)

any insights on what might cause it or what i could do ?

**Comment by vvocach** [comment]
yeah, i'm facing the same issue !

**Comment by extremeblackliu** [comment]
sorry i dont watch this repository often, you said every 5 minutes the game crash on it?
can you provide the code or poc, i tested this before i push to the repository.

**Comment by extremeblackliu** [comment]
@vvocach ^

**Comment by Mevasss** [comment]
this problem is probably caused by the fact that when creating an object, unity also searches for it, but because it is not fully created, a crash occurs. For me, this problem is completely solved by searching for objects inside OnUpdatecallback.

`static inline int stat;
static auto OnLateUpdate_callback() -> void
{
	++stat;

	if (stat >= 60) {

		auto p = Unity::Object::FindObjectsOfType<void*>("Player_move_c", false);

		std::cout << p->m_uMaxLength << std::endl;

		stat = 0;
	}

}`

**Comment by extremeblackliu** [comment]
closed for inactive and no future response.
